import os
import io
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go
import requests
from fpdf import FPDF

# Configure Page
st.set_page_config(
    page_title="EduTrack AI - SDG 4 Dashboard",
    page_icon="🎓",
    layout="wide",
    initial_sidebar_state="expanded"
)

# FastAPI URL Configuration
def get_api_url():
    # Try Streamlit Secrets first (Standard for Streamlit Cloud)
    if "API_URL" in st.secrets:
        return st.secrets["API_URL"]
    # Fallback to Environment Variable (Standard for Docker/Render)
    return os.getenv("API_URL", "http://localhost:8000")

API_URL = get_api_url()

# Custom Premium Styling
st.markdown("""
<style>
    @import url('https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;700&display=swap');
    
    html, body, [class*="css"] {
        font-family: 'Outfit', sans-serif;
    }
    
    .main-title {
        font-size: clamp(2rem, 5vw, 3.5rem);
        font-weight: 700;
        background: linear-gradient(135deg, #FF4B4B, #FF8F8F);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        margin-bottom: 0.5rem;
        line-height: 1.2;
    }
    
    .subtitle {
        font-size: clamp(1rem, 2vw, 1.2rem);
        color: #6c757d;
        margin-bottom: 2rem;
    }
    
    .metric-card {
        background: white;
        padding: 1.5rem;
        border-radius: 12px;
        box-shadow: 0 4px 6px rgba(0,0,0,0.05);
        border: 1px solid #eaeaea;
        transition: transform 0.2s;
        height: 100%;
    }
    
    @media (max-width: 768px) {
        .main-title { font-size: 2.2rem; }
        .metric-card { padding: 1rem; }
    }
    
    .metric-card:hover {
        transform: translateY(-5px);
    }
    
    .status-badge {
        padding: 4px 8px;
        border-radius: 20px;
        font-size: 0.8rem;
        font-weight: 600;
        display: inline-block;
    }
    
    .status-safe {
        background-color: #d1e7dd;
        color: #0f5132;
    }
    
    .status-warning {
        background-color: #fff3cd;
        color: #664d03;
    }
    
    .status-danger {
        background-color: #f8d7da;
        color: #842029;
    }
</style>
""", unsafe_allow_html=True)

# Helper function to check backend health
def check_backend():
    try:
        response = requests.get(API_URL, timeout=2)
        if response.status_code == 200:
            return True, response.json().get("model_loaded", False)
    except:
        pass
    return False, False

# PDF Generator Class
class StudentReportPDF(FPDF):
    def __init__(self, student_name, student_id):
        super().__init__()
        self.student_name = student_name
        self.student_id = student_id
        
    def header(self):
        # Header banner
        self.set_fill_color(31, 41, 55) # Dark gray
        self.rect(0, 0, 210, 35, 'F')
        
        self.set_text_color(255, 255, 255)
        self.set_font('helvetica', 'B', 20)
        self.cell(0, 5, 'EduTrack AI', border=False, ln=True, align='L')
        self.set_font('helvetica', 'I', 10)
        self.cell(0, 8, 'SDG 4 Capstone - Early Academic Risk & Intervention Plan', border=False, ln=True, align='L')
        self.ln(10)
        
    def footer(self):
        # Footer
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Generated by EduTrack AI | Page {self.page_no()}/{{nb}}', border=0, ln=False, align='C')

def generate_pdf_bytes(student_name, student_id, records, weakest_subject, recommendations):
    pdf = StudentReportPDF(student_name, student_id)
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Student Info Card
    pdf.set_y(40)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('helvetica', 'B', 14)
    pdf.cell(0, 10, 'Student Profile', ln=True)
    pdf.set_font('helvetica', '', 11)
    
    pdf.set_fill_color(245, 247, 250)
    pdf.cell(95, 8, f'  Name: {student_name}', border=1, fill=True)
    pdf.cell(95, 8, f'  Student ID: {student_id}', border=1, ln=True, fill=True)
    
    # Calculate Overall Stats
    midterms = [r['midterm_score'] for r in records]
    attendances = [r['attendance_rate'] for r in records]
    avg_midterm = np.mean(midterms)
    avg_attendance = np.mean(attendances)
    
    pdf.cell(95, 8, f'  Average Midterm: {avg_midterm:.1f}%', border=1, fill=True)
    pdf.cell(95, 8, f'  Average Attendance: {avg_attendance:.1f}%', border=1, ln=True, fill=True)
    
    pdf.ln(8)
    
    # Subject Performance Table Header
    pdf.set_font('helvetica', 'B', 14)
    pdf.cell(0, 10, 'Subject Performance & Predicted Risk', ln=True)
    
    pdf.set_font('helvetica', 'B', 10)
    pdf.set_fill_color(230, 230, 230)
    pdf.cell(45, 8, 'Subject', border=1, align='C', fill=True)
    pdf.cell(25, 8, 'Midterm %', border=1, align='C', fill=True)
    pdf.cell(25, 8, 'Attendance %', border=1, align='C', fill=True)
    pdf.cell(25, 8, 'Study Hours', border=1, align='C', fill=True)
    pdf.cell(25, 8, 'Past Score %', border=1, align='C', fill=True)
    pdf.cell(45, 8, 'Predicted Risk Prob.', border=1, ln=True, align='C', fill=True)
    
    pdf.set_font('helvetica', '', 10)
    for record in records:
        pdf.cell(45, 8, f" {record['subject']}", border=1)
        pdf.cell(25, 8, f"{record['midterm_score']}%", border=1, align='C')
        pdf.cell(25, 8, f"{record['attendance_rate']}%", border=1, align='C')
        pdf.cell(25, 8, f"{record['study_hours']}h/wk", border=1, align='C')
        pdf.cell(25, 8, f"{record['past_score']}%", border=1, align='C')
        
        # Color-code risk probability
        prob = record.get('risk_prob', 0.0)
        risk_text = f"{prob*100:.1f}%"
        if prob >= 0.7:
            pdf.set_text_color(200, 30, 30) # Red
        elif prob >= 0.3:
            pdf.set_text_color(220, 100, 0) # Orange
        else:
            pdf.set_text_color(30, 120, 30) # Green
            
        pdf.cell(45, 8, risk_text, border=1, ln=True, align='C')
        pdf.set_text_color(0, 0, 0) # Reset color
        
    pdf.ln(8)
    
    # Recommendation Section
    pdf.set_fill_color(255, 243, 205) # Yellow alert card background
    pdf.rect(10, pdf.get_y(), 190, 45, 'F')
    
    pdf.set_y(pdf.get_y() + 2)
    pdf.set_font('helvetica', 'B', 12)
    pdf.set_text_color(102, 77, 3) # Brownish
    pdf.cell(0, 6, '  INTERVENTION PLAN & RECOMMENDATIONS', ln=True)
    pdf.set_font('helvetica', '', 10)
    pdf.set_text_color(0, 0, 0)
    
    pdf.cell(0, 6, f'  - Weakest Subject Identified: {weakest_subject}', ln=True)
    pdf.cell(0, 6, f"  - Intervention Recommendation: {recommendations.get('weakest_subject_recommendation', 'N/A')}", ln=True)
    pdf.cell(0, 6, f"  - Study Guideline: {recommendations.get('study_hours_recommendation', 'N/A')}", ln=True)
    
    pdf.ln(15)
    pdf.set_font('helvetica', 'I', 9)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 4, "Disclaimer: These recommendations are generated by EduTrack AI using historical class performance data. They serve as supportive guide rails for teachers and students to plan academic intervention.", align='C')
    
    return bytes(pdf.output())

# Sidebar Navigation and Connection Status
st.sidebar.markdown("<h2 style='text-align: center;'>EduTrack AI</h2>", unsafe_allow_html=True)
st.sidebar.markdown("<p style='text-align: center; color: gray;'>SDG 4 (Quality Education) Capstone</p>", unsafe_allow_html=True)
st.sidebar.markdown("---")

backend_alive, model_loaded = check_backend()

# Sidebar Connection Info
st.sidebar.subheader("System Status")
if backend_alive:
    st.sidebar.markdown('API Status: <span class="status-badge status-safe">Connected</span>', unsafe_allow_html=True)
    if model_loaded:
        st.sidebar.markdown('ML Model: <span class="status-badge status-safe">Loaded</span>', unsafe_allow_html=True)
    else:
        st.sidebar.markdown('ML Model: <span class="status-badge status-warning">Not Trained</span>', unsafe_allow_html=True)
else:
    st.sidebar.markdown('API Status: <span class="status-badge status-danger">Disconnected</span>', unsafe_allow_html=True)
    st.sidebar.warning(f"FastAPI backend ({API_URL}) is offline. Please ensure the backend server is running and the API_URL is correctly configured in Streamlit Secrets.")

st.sidebar.markdown("---")
page = st.sidebar.radio(
    "Navigation", 
    ["Overview Dashboard", "Individual Lookup", "Risk Sandbox", "Dataset Manager"]
)

# Render Pages
if page == "Overview Dashboard":
    st.markdown('<div class="main-title">EduTrack AI Analytics</div>', unsafe_allow_html=True)
    st.markdown('<div class="subtitle">Real-time overview of class academic risk distribution matching SDG 4 metrics.</div>', unsafe_allow_html=True)
    
    if not backend_alive:
        st.error("Cannot load dashboard metrics. FastAPI backend is disconnected.")
        # Fallback to local CSV if exists
        csv_fallback = "D:/lenovo LEAP/Capstone Project/data/student_data.csv"
        if os.path.exists(csv_fallback):
            st.info("Displaying static view from local data/student_data.csv fallback.")
            df = pd.read_csv(csv_fallback)
            
            # Simple metrics
            total_students = df['StudentID'].nunique()
            avg_attendance = df['Attendance_Rate'].mean()
            avg_midterm = df['Midterm_Score'].mean()
            at_risk_count = df[df['At_Risk'] == 1].shape[0]
            
            col1, col2, col3, col4 = st.columns(4)
            col1.metric("Total Students", total_students)
            col2.metric("Avg Attendance", f"{avg_attendance:.1f}%")
            col3.metric("Avg Midterm Score", f"{avg_midterm:.1f}%")
            col4.metric("At Risk Subjects Count", at_risk_count)
            
            # Chart 1: Subject Performance
            fig_sub = px.bar(
                df.groupby('Subject')['Midterm_Score'].mean().reset_index(),
                x='Subject', y='Midterm_Score',
                title="Class Average Midterm Score by Subject",
                labels={'Midterm_Score': 'Average Score (%)'}
            )
            st.plotly_chart(fig_sub, use_container_width=True)
        else:
            st.warning("No fallback CSV found. Please run data generator or upload data.")
    else:
        # Load from API
        with st.spinner("Fetching data from API..."):
            records_res = requests.get(f"{API_URL}/records")
            stats_res = requests.get(f"{API_URL}/class-stats")
            
            if records_res.status_code == 200 and stats_res.status_code == 200:
                all_records = records_res.json()
                stats_data = stats_res.json()
                
                df_records = pd.DataFrame(all_records)
                df_stats = pd.DataFrame(stats_data)
                
                if df_records.empty:
                    st.warning("The database is currently empty. Please go to the 'Dataset Manager' tab and upload the student dataset to begin.")
                    st.info("Sample file can be found at data/student_data.csv in the repository.")
                    st.stop()
                
                # Calculate metrics
                total_students = df_records['student_id'].nunique()
                avg_attendance = df_records['attendance_rate'].mean()
                avg_midterm = df_records['midterm_score'].mean()
                
                # Fetch predictions in a single batch call if model is loaded
                risk_counts = {'High Risk (>=70%)': 0, 'Medium Risk (30-70%)': 0, 'Low Risk (<30%)': 0}
                all_predicted_records = []
                
                if model_loaded and not df_records.empty:
                    # Single batch predict
                    pred_req = {"records": [
                        {
                            "Subject": r['subject'],
                            "Attendance_Rate": float(r['attendance_rate']),
                            "Study_Hours": float(r['study_hours']),
                            "Midterm_Score": float(r['midterm_score']),
                            "Past_Score": float(r['past_score'])
                        } for _, r in df_records.iterrows()
                    ]}
                    
                    try:
                        pred_res = requests.post(f"{API_URL}/predict", json=pred_req)
                        if pred_res.status_code == 200:
                            preds = pred_res.json()['predictions']
                            for i, p in enumerate(preds):
                                prob = p['Risk_Probability']
                                row_data = df_records.iloc[i]
                                
                                if prob >= 0.7:
                                    risk_counts['High Risk (>=70%)'] += 1
                                    all_predicted_records.append({
                                        "StudentID": int(row_data['student_id']),
                                        "Name": row_data['name'],
                                        "Subject": row_data['subject'],
                                        "Midterm": row_data['midterm_score'],
                                        "Attendance": row_data['attendance_rate'],
                                        "Risk": f"{prob*100:.1f}%",
                                        "RiskVal": prob
                                    })
                                elif prob >= 0.3:
                                    risk_counts['Medium Risk (30-70%)'] += 1
                                else:
                                    risk_counts['Low Risk (<30%)'] += 1
                        else:
                            model_loaded = False
                    except Exception as e:
                        model_loaded = False
                        
                if not model_loaded or df_records.empty:
                    # Fallback to database `at_risk` field (actual labels)
                    for _, row_data in df_records.iterrows():
                        val = row_data['at_risk']
                        if val == 1:
                            risk_counts['High Risk (>=70%)'] += 1
                            all_predicted_records.append({
                                "StudentID": int(row_data['student_id']),
                                "Name": row_data['name'],
                                "Subject": row_data['subject'],
                                "Midterm": row_data['midterm_score'],
                                "Attendance": row_data['attendance_rate'],
                                "Risk": "100.0% (Failed)",
                                "RiskVal": 1.0
                            })
                        else:
                            risk_counts['Low Risk (<30%)'] += 1
                            
                total_risk_subjects = len(all_predicted_records)
                
                # Layout metrics
                col1, col2, col3, col4 = st.columns(4)
                with col1:
                    st.markdown(f"""
                    <div class="metric-card">
                        <p style="color: gray; margin: 0; font-size: 0.9rem;">Total Students</p>
                        <h2 style="margin: 0.5rem 0 0 0; font-size: 2.2rem; font-weight: 600;">{total_students}</h2>
                    </div>
                    """, unsafe_allow_html=True)
                with col2:
                    st.markdown(f"""
                    <div class="metric-card">
                        <p style="color: gray; margin: 0; font-size: 0.9rem;">Avg Attendance</p>
                        <h2 style="margin: 0.5rem 0 0 0; font-size: 2.2rem; font-weight: 600; color: #0d6efd;">{avg_attendance:.1f}%</h2>
                    </div>
                    """, unsafe_allow_html=True)
                with col3:
                    st.markdown(f"""
                    <div class="metric-card">
                        <p style="color: gray; margin: 0; font-size: 0.9rem;">Avg Midterm Score</p>
                        <h2 style="margin: 0.5rem 0 0 0; font-size: 2.2rem; font-weight: 600; color: #198754;">{avg_midterm:.1f}%</h2>
                    </div>
                    """, unsafe_allow_html=True)
                with col4:
                    st.markdown(f"""
                    <div class="metric-card">
                        <p style="color: gray; margin: 0; font-size: 0.9rem;">At-Risk Instances</p>
                        <h2 style="margin: 0.5rem 0 0 0; font-size: 2.2rem; font-weight: 600; color: #dc3545;">{total_risk_subjects}</h2>
                    </div>
                    """, unsafe_allow_html=True)
                
                st.markdown("<br>", unsafe_allow_html=True)
                
                # Visualizations
                char_col1, char_col2 = st.columns(2)
                
                with char_col1:
                    # Class average by subject
                    fig_sub = px.bar(
                        df_stats, x='subject', y='avg_midterm',
                        title="Class Average Midterm Score by Subject",
                        color='avg_midterm',
                        color_continuous_scale=px.colors.sequential.Reds,
                        labels={'avg_midterm': 'Midterm Score (%)', 'subject': 'Subject'},
                        height=400
                    )
                    fig_sub.update_layout(showlegend=False)
                    st.plotly_chart(fig_sub, use_container_width=True)
                    
                with char_col2:
                    # Pie chart risk
                    labels = list(risk_counts.keys())
                    values = list(risk_counts.values())
                    
                    fig_pie = px.pie(
                        names=labels, values=values,
                        title="Student Risk Classification Distribution (All Student-Subject Pairs)",
                        color=labels,
                        color_discrete_map={
                            'High Risk (>=70%)': '#dc3545',
                            'Medium Risk (30-70%)': '#fd7e14',
                            'Low Risk (<30%)': '#198754'
                        },
                        height=400
                    )
                    st.plotly_chart(fig_pie, use_container_width=True)
                
                # At Risk Students Table
                st.markdown("### ⚠️ Student Academic Risk List")
                st.markdown("This table lists individual student-subject entries flagged as **High Risk** (probability of failing final exam >= 70%, or already marked as failed/at-risk in the uploaded historical dataset).")
                
                if all_predicted_records:
                    df_risk_list = pd.DataFrame(all_predicted_records)
                    # Sort by risk probability descending
                    df_risk_list = df_risk_list.sort_values(by="RiskVal", ascending=False)
                    st.dataframe(
                        df_risk_list[['StudentID', 'Name', 'Subject', 'Midterm', 'Attendance', 'Risk']],
                        use_container_width=True,
                        hide_index=True
                    )
                else:
                    st.success("No students are flagged as High Risk!")
            else:
                st.error("Failed to load statistics from API.")

elif page == "Individual Lookup":
    st.markdown('<div class="main-title">Student Profile Lookup</div>', unsafe_allow_html=True)
    st.markdown('<div class="subtitle">Search for a student to check their performance, predict subject-specific risks, and generate report cards.</div>', unsafe_allow_html=True)
    
    if not backend_alive:
        st.error("Lookup functionality unavailable. FastAPI backend is disconnected.")
    else:
        # Fetch students
        students_res = requests.get(f"{API_URL}/students")
        if students_res.status_code == 200:
            students = students_res.json()
            student_list = [f"{s['name']} (ID: {s['student_id']})" for s in students]
            
            selected_student_str = st.selectbox("Select Student", student_list)
            
            if selected_student_str:
                student_id = int(selected_student_str.split("ID: ")[1].split(")")[0])
                
                # Fetch detail
                detail_res = requests.get(f"{API_URL}/students/{student_id}")
                if detail_res.status_code == 200:
                    detail = detail_res.json()
                    name = detail['name']
                    records = detail['records']
                    
                    # Compute Predictions if model is loaded
                    for i, r in enumerate(records):
                        if model_loaded:
                            pred_req = {
                                "records": [{
                                    "Subject": r['subject'],
                                    "Attendance_Rate": r['attendance_rate'],
                                    "Study_Hours": r['study_hours'],
                                    "Midterm_Score": r['midterm_score'],
                                    "Past_Score": r['past_score']
                                }]
                            }
                            pred_res = requests.post(f"{API_URL}/predict", json=pred_req)
                            if pred_res.status_code == 200:
                                r['risk_prob'] = pred_res.json()['predictions'][0]['Risk_Probability']
                            else:
                                r['risk_prob'] = 1.0 if r['at_risk'] == 1 else 0.0
                        else:
                            r['risk_prob'] = 1.0 if r['at_risk'] == 1 else 0.0
                            
                    # Display Student Info Card
                    df_rec = pd.DataFrame(records)
                    avg_midterm = df_rec['midterm_score'].mean()
                    avg_attendance = df_rec['attendance_rate'].mean()
                    
                    st.markdown(f"### Student Profile: **{name}** (ID: {student_id})")
                    col1, col2, col3 = st.columns(3)
                    col1.metric("Overall Midterm Avg", f"{avg_midterm:.1f}%")
                    col2.metric("Overall Attendance Avg", f"{avg_attendance:.1f}%")
                    col3.metric("Total Subjects", len(df_rec))
                    
                    st.markdown("---")
                    st.subheader("Academic Performance & Risk Breakdown")
                    
                    # Columns to display nicely
                    disp_records = []
                    class_averages = {row['subject']: row['avg_midterm'] for row in requests.get(f"{API_URL}/class-stats").json()}
                    
                    # Identifying weakest subject
                    # Rule: lowest score vs class average
                    weakest_diff = float('inf')
                    weakest_sub = "None"
                    weakest_score = 100
                    
                    for r in records:
                        subj = r['subject']
                        score = r['midterm_score']
                        class_avg = class_averages.get(subj, 65.0)
                        diff = score - class_avg
                        
                        if diff < weakest_diff:
                            weakest_diff = diff
                            weakest_sub = subj
                            weakest_score = score
                            
                        # Formatting status badge
                        prob = r.get('risk_prob', 0.0)
                        if prob >= 0.7:
                            status_html = f'<span class="status-badge status-danger">High Risk ({prob*100:.1f}%)</span>'
                        elif prob >= 0.3:
                            status_html = f'<span class="status-badge status-warning">Medium Risk ({prob*100:.1f}%)</span>'
                        else:
                            status_html = f'<span class="status-badge status-safe">Low Risk ({prob*100:.1f}%)</span>'
                            
                        disp_records.append({
                            "Subject": subj,
                            "Midterm Score (%)": f"{score}%",
                            "Class Average (%)": f"{class_avg}%",
                            "Diff vs Average": f"{diff:+.1f}%",
                            "Attendance Rate": f"{r['attendance_rate']}%",
                            "Study Hours (h/wk)": r['study_hours'],
                            "Predicted Risk": status_html
                        })
                        
                    # Show performance table
                    st.write(
                        pd.DataFrame(disp_records).to_html(escape=False, index=False),
                        unsafe_allow_html=True
                    )
                    st.markdown("<br>", unsafe_allow_html=True)
                    
                    # Intervention Panel
                    st.markdown("### 🛠️ SDG 4 Academic Intervention Plan")
                    
                    rec_col1, rec_col2 = st.columns(2)
                    with rec_col1:
                        st.info(f"**Weakest Subject**: {weakest_sub} ({weakest_score}% score, which is {weakest_diff:+.1f}% compared to the class average).")
                        
                        # Generate recommendation
                        # rule-based: if score < 50% → +5 hrs/week, etc.
                        rec_hours = 0
                        if weakest_score < 50:
                            rec_hours = 5
                            rec_txt = f"Critical concern. Weakest subject is {weakest_sub} where score is failing (<50%)."
                        elif weakest_score < 70:
                            rec_hours = 3
                            rec_txt = f"Warning. Weakest subject is {weakest_sub} where score is borderline (50-70%)."
                        elif weakest_score < 85:
                            rec_hours = 1.5
                            rec_txt = f"Moderate. Weakest subject is {weakest_sub} with a passing but average score (70-85%)."
                        else:
                            rec_hours = 0
                            rec_txt = f"Excellent! The student's weakest subject is {weakest_sub} with a score of {weakest_score}%, indicating solid baseline performance across the board."
                            
                        st.markdown(f"**Status Analysis**: {rec_txt}")
                        
                        study_hours_rec = ""
                        if rec_hours > 0:
                            study_hours_rec = f"Recommend increasing weekly study hours for {weakest_sub} by **+{rec_hours} hours/week** (minimum total of {df_rec[df_rec['subject'] == weakest_sub]['study_hours'].values[0] + rec_hours} hours/week) to mitigate fail risk."
                        else:
                            study_hours_rec = "Keep up the great work! Maintain current study habits and review concepts regularly."
                            
                        st.markdown(f"**Intervention Guideline**: {study_hours_rec}")
                        
                    with rec_col2:
                        # Report exports
                        st.markdown("#### Export Report Card")
                        st.markdown("Download a summary PDF or CSV report including the student profile, detailed scores, and the generated academic intervention recommendations.")
                        
                        rec_dict = {
                            "weakest_subject_recommendation": rec_txt,
                            "study_hours_recommendation": study_hours_rec
                        }
                        
                        # PDF generation
                        pdf_bytes = generate_pdf_bytes(name, student_id, records, weakest_sub, rec_dict)
                        
                        st.download_button(
                            label="📄 Download PDF Report Card",
                            data=pdf_bytes,
                            file_name=f"edutrack_report_{student_id}.pdf",
                            mime="application/pdf",
                            key=f"pdf_btn_{student_id}"
                        )
                        
                        # CSV generation
                        csv_df = pd.DataFrame(records)
                        csv_df['Student_Name'] = name
                        csv_df['Weakest_Subject'] = weakest_sub
                        csv_df['Weekly_Study_Hours_Recommendation'] = study_hours_rec
                        csv_data = csv_df.to_csv(index=False)
                        
                        st.download_button(
                            label="📊 Download CSV Performance Data",
                            data=csv_data,
                            file_name=f"edutrack_student_{student_id}.csv",
                            mime="text/csv",
                            key=f"csv_btn_{student_id}"
                        )
                else:
                    st.error("Error fetching student details.")
        else:
            st.error("Failed to load student list.")

elif page == "Risk Sandbox":
    st.markdown('<div class="main-title">Risk Prediction Sandbox</div>', unsafe_allow_html=True)
    st.markdown('<div class="subtitle">Simulate student profiles to calculate real-time probability of academic risk. Useful for testing hypothetical school interventions.</div>', unsafe_allow_html=True)
    
    if not backend_alive or not model_loaded:
        st.error("Model sandbox is unavailable. Make sure the FastAPI backend is online and the ML model is trained.")
    else:
        # Form input
        col1, col2 = st.columns(2)
        with col1:
            subject = st.selectbox("Subject", ["Math", "Science", "English", "History", "Computer Science"])
            attendance = st.slider("Attendance Rate (%)", 30, 100, 85)
            study_hours = st.slider("Weekly Study Hours", 1, 15, 5)
            midterm_score = st.slider("Midterm Score (%)", 10, 100, 60)
            past_score = st.slider("Past Class Score (%)", 10, 100, 65)
            
            submit_btn = st.button("Predict Academic Risk")
            
        with col2:
            if submit_btn:
                pred_req = {
                    "records": [{
                        "Subject": subject,
                        "Attendance_Rate": float(attendance),
                        "Study_Hours": float(study_hours),
                        "Midterm_Score": float(midterm_score),
                        "Past_Score": float(past_score)
                    }]
                }
                
                with st.spinner("Calculating risk via ensemble model..."):
                    pred_res = requests.post(f"{API_URL}/predict", json=pred_req)
                    
                    if pred_res.status_code == 200:
                        pred_val = pred_res.json()['predictions'][0]
                        prob = pred_val['Risk_Probability']
                        at_risk = pred_val['At_Risk']
                        
                        st.markdown("### Prediction Results")
                        
                        # Gauge plot or simple probability display
                        fig = go.Figure(go.Indicator(
                            mode = "gauge+number",
                            value = prob * 100,
                            domain = {'x': [0, 1], 'y': [0, 1]},
                            title = {'text': "Predicted Failure Probability (%)", 'font': {'size': 18}},
                            gauge = {
                                'axis': {'range': [None, 100], 'tickwidth': 1, 'tickcolor': "darkblue"},
                                'bar': {'color': "#333"},
                                'bgcolor': "white",
                                'borderwidth': 2,
                                'bordercolor': "gray",
                                'steps': [
                                    {'range': [0, 30], 'color': '#d1e7dd'}, # Green
                                    {'range': [30, 70], 'color': '#fff3cd'}, # Yellow
                                    {'range': [70, 100], 'color': '#f8d7da'} # Red
                                ],
                            }
                        ))
                        fig.update_layout(height=250, margin=dict(t=0, b=0, l=10, r=10))
                        st.plotly_chart(fig, use_container_width=True)
                        
                        if prob >= 0.7:
                            st.error(f"⚠️ **HIGH RISK ({prob*100:.1f}%)**: This student is flagged as high-risk. Prompt intervention is recommended.")
                        elif prob >= 0.3:
                            st.warning(f"⚡ **MEDIUM RISK ({prob*100:.1f}%)**: This student shows warning signs. Keep a close watch.")
                        else:
                            st.success(f"✅ **LOW RISK ({prob*100:.1f}%)**: The student appears to be safe and on track to pass.")
                            
                        # Sandbox Recommendations
                        rec_hours = 0
                        if midterm_score < 50:
                            rec_hours = 5
                        elif midterm_score < 70:
                            rec_hours = 3
                        elif midterm_score < 85:
                            rec_hours = 1.5
                            
                        st.markdown("#### Intervention Scenario Planner")
                        if rec_hours > 0:
                            st.markdown(f"- **Recommended Study Increase**: +{rec_hours} hrs/week (Increase study hours from {study_hours} to {study_hours + rec_hours} hrs/week).")
                            if attendance < 85:
                                st.markdown("- **Recommended Attendance Increase**: Boost attendance rate above 85% to improve final exam performance.")
                        else:
                            st.markdown("- **Recommendation**: The student's current parameters indicate a stable prediction. Encourage maintaining current study hours and attendance.")
                    else:
                        st.error("Prediction failed. Please check backend logs.")

elif page == "Dataset Manager":
    st.markdown('<div class="main-title">Dataset Manager</div>', unsafe_allow_html=True)
    st.markdown('<div class="subtitle">Upload school datasets (CSV) to refresh database records and trigger automated ML model retraining.</div>', unsafe_allow_html=True)
    
    st.markdown("""
    #### Expected CSV Format
    Your uploaded CSV must contain the following columns:
    `StudentID`, `Name`, `Subject`, `Attendance_Rate`, `Study_Hours`, `Midterm_Score`, `Past_Score`, `Final_Score`, `At_Risk`
    """)
    
    # Download sample template
    sample_csv_path = "D:/lenovo LEAP/Capstone Project/data/student_data.csv"
    if os.path.exists(sample_csv_path):
        sample_df = pd.read_csv(sample_csv_path).head(5)
        st.markdown("**Sample Format Preview:**")
        st.dataframe(sample_df, hide_index=True)
        
        with open(sample_csv_path, "rb") as f:
            st.download_button(
                "📥 Download Sample Student CSV",
                f.read(),
                "sample_student_data.csv",
                "text/csv"
            )
            
    st.markdown("---")
    
    if not backend_alive:
        st.error("Upload interface disabled. FastAPI backend must be connected to receive files and train models.")
    else:
        uploaded_file = st.file_uploader("Choose a CSV file", type="csv")
        
        if uploaded_file is not None:
            # File info
            df_uploaded = pd.read_csv(uploaded_file)
            st.success(f"Loaded {uploaded_file.name} successfully. Found {len(df_uploaded)} student records.")
            
            # Check required columns
            required_cols = ['StudentID', 'Name', 'Subject', 'Attendance_Rate', 'Study_Hours', 'Midterm_Score', 'Past_Score', 'Final_Score', 'At_Risk']
            missing_cols = [c for c in required_cols if c not in df_uploaded.columns]
            
            if missing_cols:
                st.error(f"Invalid dataset columns! Missing: {', '.join(missing_cols)}")
            else:
                if st.button("🚀 Upload & Retrain System Model"):
                    # Prepare upload post
                    uploaded_file.seek(0)
                    files = {"file": (uploaded_file.name, uploaded_file.read(), "text/csv")}
                    
                    with st.spinner("Uploading file, updating SQLite tables, and retraining the ML model ensemble..."):
                        try:
                            upload_res = requests.post(f"{API_URL}/upload", files=files)
                            if upload_res.status_code == 200:
                                st.success("✅ Dataset uploaded and system updated successfully!")
                                st.json(upload_res.json())
                            else:
                                st.error(f"Error from server: {upload_res.json().get('detail', 'Unknown error')}")
                        except Exception as e:
                            st.error(f"Network error during upload: {e}")
                            
        st.markdown("---")
        st.markdown("#### Force Model Retraining")
        st.markdown("If you manually modified the SQLite database, click the button below to force the backend to retrain the Random Forest + Logistic Regression ensemble model.")
        if st.button("🔄 Force Retrain Model"):
            with st.spinner("Retraining..."):
                try:
                    retrain_res = requests.post(f"{API_URL}/retrain")
                    if retrain_res.status_code == 200:
                        st.success("✅ Model retrained successfully!")
                    else:
                        st.error(f"Retraining failed: {retrain_res.json().get('detail')}")
                except Exception as e:
                    st.error(f"Network error: {e}")
